definitions:
  bannerdto.BannerResponse:
    properties:
      description:
        type: string
      name:
        type: string
      source_url:
        type: string
    type: object
  dto.CreateProjectResponse:
    properties:
      uuid:
        type: string
    type: object
  dto.ExchangeRequest:
    properties:
      firebase_id_token:
        type: string
      phone_number:
        type: string
    required:
    - firebase_id_token
    - phone_number
    type: object
  dto.ExchangeResponse:
    properties:
      token:
        type: string
    type: object
  dto.GetProfileResponse:
    properties:
      fullname:
        type: string
      image_url:
        type: string
      role:
        type: string
    type: object
  dto.ListProjectResponse:
    properties:
      astrodevs:
        items:
          $ref: '#/definitions/dto.GetProfileResponse'
        type: array
      created_at:
        type: string
      description:
        type: string
      name:
        type: string
      service_type:
        type: string
      status:
        type: string
      uuid:
        type: string
    type: object
  dto.OtpRequest:
    properties:
      phone_number:
        type: string
    required:
    - phone_number
    type: object
  dto.OtpValidateRequest:
    properties:
      otp:
        type: string
      phone_number:
        type: string
    required:
    - otp
    - phone_number
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      phone_number:
        type: string
      type:
        type: string
    required:
    - email
    - fullname
    - phone_number
    type: object
  dto.UpdateProjectReq:
    properties:
      deadline_type:
        type: integer
      description:
        type: string
      name:
        type: string
      service_type:
        type: integer
    type: object
  pkg.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      meta:
        $ref: '#/definitions/pkg.MetaResponse'
    type: object
  pkg.MetaResponse:
    properties:
      page:
        type: integer
      per_page:
        type: integer
    type: object
info:
  contact:
    email: mail@codespace.id
    name: Codespace Indonesia
    url: https://codespace.id
  description: Codespace X
  title: Codespace X REST API
  version: "1.0"
paths:
  /api/v1/auth/exchange-token:
    post:
      consumes:
      - application/json
      description: Exchange Token
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: payload exchange token
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.ExchangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.ExchangeResponse'
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Exchange Token
      tags:
      - Auth
  /api/v1/auth/otp/request:
    post:
      consumes:
      - application/json
      description: OTP Request
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: payload otp request
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: OTP Request
      tags:
      - Auth
  /api/v1/auth/otp/resend:
    post:
      consumes:
      - application/json
      description: OTP Resend
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: payload otp request resend
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: OTP Resend
      tags:
      - Auth
  /api/v1/auth/otp/validate:
    post:
      consumes:
      - application/json
      description: OTP Validate
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: payload otp request
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.OtpValidateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: OTP Validate
      tags:
      - Auth
  /api/v1/auth/phone/verify:
    post:
      consumes:
      - application/json
      description: Used when register before hit register button
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: payload otp request resend
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Phone Verification
      tags:
      - Auth
  /api/v1/banners:
    get:
      consumes:
      - application/json
      description: List Banner
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/bannerdto.BannerResponse'
                  type: array
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: List Banner
      tags:
      - Banner
  /api/v1/notifications:
    get:
      consumes:
      - application/json
      description: List Notif
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: List Notif
      tags:
      - Notifications
  /api/v1/projects:
    get:
      consumes:
      - application/json
      description: List Project
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.ListProjectResponse'
                  type: array
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: List Project
      tags:
      - Projects
    post:
      consumes:
      - application/json
      description: Create Project
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      - description: userdto.RegisterRequest
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.CreateProjectResponse'
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Create Project
      tags:
      - Projects
  /api/v1/projects/{project_uuid}:
    get:
      consumes:
      - application/json
      description: Detail Project
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      - description: project_uuid
        in: path
        name: project_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.ListProjectResponse'
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Detail Project
      tags:
      - Projects
    patch:
      consumes:
      - application/json
      description: Update Project
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      - description: dto.UpdateProjectReq
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateProjectReq'
      - description: uuid project
        in: path
        name: project_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Update Project
      tags:
      - Projects
  /api/v1/users/profile:
    get:
      consumes:
      - application/json
      description: Get Profile
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.GetProfileResponse'
              type: object
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Get Profile
      tags:
      - User
  /api/v1/users/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: X-Service-Auth-Token
        in: header
        name: X-Service-Auth-Token
        required: true
        type: string
      - description: Authorization value
        in: header
        name: authorization
        required: true
        type: string
      - description: dto.RegisterRequest
        in: body
        name: body-payload
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
        default:
          description: error
          schema:
            $ref: '#/definitions/pkg.BaseResponse'
      summary: Register
      tags:
      - User
swagger: "2.0"
